INSERT INTO Products([Name], [Unit]) VALUES('water', 1);
INSERT INTO Products([Name], [Unit]) VALUES('black tea', 2);
INSERT INTO Products([Name], [Unit]) VALUES('milk', 1);
INSERT INTO Products([Name], [Unit]) VALUES('salt', 0);
INSERT INTO Products([Name], [Unit]) VALUES('sugar', 0);
INSERT INTO Products([Name], [Unit]) VALUES('bread', 0);
INSERT INTO Products([Name], [Unit]) VALUES('butter', 0);
INSERT INTO Products([Name], [Unit]) VALUES('lemon', 0);
INSERT INTO Products([Name], [Unit]) VALUES('apple', 0);
INSERT INTO Products([Name], [Unit]) VALUES('tomato', 0);