name: API-CI

on:
  pull_request:
    branches: [ master ]
    types: [opened, reopened, edited]

jobs:
  build:
    runs-on: windows

    steps:
    - name: "Checkout"
      uses: actions/checkout@v1
    - name: "Test"
      run: dir
